### ISSUE TITLE
Angular-CLI AOT compilation failed

### ISSUE THREAD

**Issue by FabienDehopre** [PointInside/ng2-toastr#100]
When using ng2-toastr in an angular-cli project, the AOT compilation fails with this message:
```
 ng build --prod --aot
  0% compilingError encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in c:/Users/f.dehopre/devs/Portal/frontend/website/src/app/app.module.ts, resolving symbol AppModule in c:/Users/f.dehopre/devs/Portal/frontend/website/src/app/app.module.ts
Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in c:/Users/f.dehopre/devs/Portal/frontend/website/src/app/app.module.ts, resolving symbol AppModule in c:/Users/f.dehopre/devs/Portal/frontend/website/src/app/app.module.ts
    at simplifyInContext (c:\Users\chuckj\src\angular\modules\@angular\compiler-cli\src\static_reflector.ts:537:15)
    at StaticReflector.simplify (c:\Users\chuckj\src\angular\modules\@angular\compiler-cli\src\static_reflector.ts:541:20)
    at StaticReflector.annotations (c:\Users\chuckj\src\angular\modules\@angular\compiler-cli\src\static_reflector.ts:93:28)
    at NgModuleResolver.resolve (c:\Users\f.dehopre\devs\Portal\frontend\website\node_modules\@angular\compiler\bundles\compiler.umd.js:14261:46)
    at CompileMetadataResolver._loadNgModuleMetadata (c:\Users\f.dehopre\devs\Portal\frontend\website\node_modules\@angular\compiler\bundles\compiler.umd.js:14646:45)
    at CompileMetadataResolver.getUnloadedNgModuleMetadata (c:\Users\f.dehopre\devs\Portal\frontend\website\node_modules\@angular\compiler\bundles\compiler.umd.js:14636:23)
    at addNgModule (c:\Users\f.dehopre\devs\Portal\frontend\website\node_modules\@angular\compiler\bundles\compiler.umd.js:12944:43)
    at c:\Users\f.dehopre\devs\Portal\frontend\website\node_modules\@angular\compiler\bundles\compiler.umd.js:12957:16
    at Array.forEach (native)
    at _createNgModules (c:\Users\f.dehopre\devs\Portal\frontend\website\node_modules\@angular\compiler\bundles\compiler.umd.js:12956:28)
    at analyzeNgModules (c:\Users\f.dehopre\devs\Portal\frontend\website\node_modules\@angular\compiler\bundles\compiler.umd.js:12700:16)
    at analyzeAndValidateNgModules (c:\Users\f.dehopre\devs\Portal\frontend\website\node_modules\@angular\compiler\bundles\compiler.umd.js:12704:20)
    at OfflineCompiler.compileModules (c:\Users\f.dehopre\devs\Portal\frontend\website\node_modules\@angular\compiler\bundles\compiler.umd.js:12775:20)
    at CodeGenerator.codegen (c:\Users\chuckj\src\angular\modules\@angular\compiler-cli\src\codegen.ts:71:26)
    at AotPlugin._make (c:\Users\f.dehopre\devs\Portal\frontend\website\node_modules\@ngtools\webpack\src\plugin.js:193:43)
    at Compiler.<anonymous> (c:\Users\f.dehopre\devs\Portal\frontend\website\node_modules\@ngtools\webpack\src\plugin.js:157:75)
    at Compiler.applyPluginsParallel (c:\Users\f.dehopre\devs\Portal\frontend\website\node_modules\tapable\lib\Tapable.js:156:14)
    at Compiler.<anonymous> (c:\Users\f.dehopre\devs\Portal\frontend\website\node_modules\webpack\lib\Compiler.js:463:8)
    at Compiler.applyPluginsAsync (c:\Users\f.dehopre\devs\Portal\frontend\website\node_modules\tapable\lib\Tapable.js:73:70)
    at Compiler.compile (c:\Users\f.dehopre\devs\Portal\frontend\website\node_modules\webpack\lib\Compiler.js:456:7)
    at Compiler.<anonymous> (c:\Users\f.dehopre\devs\Portal\frontend\website\node_modules\webpack\lib\Compiler.js:219:10)
    at Compiler.readRecords (c:\Users\f.dehopre\devs\Portal\frontend\website\node_modules\webpack\lib\Compiler.js:367:10)
    at Compiler.<anonymous> (c:\Users\f.dehopre\devs\Portal\frontend\website\node_modules\webpack\lib\Compiler.js:216:9)
    at next (c:\Users\f.dehopre\devs\Portal\frontend\website\node_modules\tapable\lib\Tapable.js:81:11)
    at Compiler.<anonymous> (c:\Users\f.dehopre\devs\Portal\frontend\website\node_modules\webpack\lib\CachePlugin.js:34:58)
    at Compiler.applyPluginsAsync (c:\Users\f.dehopre\devs\Portal\frontend\website\node_modules\tapable\lib\Tapable.js:85:13)
    at Compiler.<anonymous> (c:\Users\f.dehopre\devs\Portal\frontend\website\node_modules\webpack\lib\Compiler.js:213:8)
    at next (c:\Users\f.dehopre\devs\Portal\frontend\website\node_modules\tapable\lib\Tapable.js:81:11)
    at Compiler.<anonymous> (c:\Users\f.dehopre\devs\Portal\frontend\website\node_modules\webpack\lib\node\NodeEnvironmentPlugin.js:23:3)
    at Compiler.applyPluginsAsync (c:\Users\f.dehopre\devs\Portal\frontend\website\node_modules\tapable\lib\Tapable.js:85:13)
    at Compiler.run (c:\Users\f.dehopre\devs\Portal\frontend\website\node_modules\webpack\lib\Compiler.js:210:7)
    at c:\Users\f.dehopre\devs\Portal\frontend\website\node_modules\angular-cli\tasks\build-webpack.js:24:29
    at Class.run (c:\Users\f.dehopre\devs\Portal\frontend\website\node_modules\angular-cli\tasks\build-webpack.js:23:16)
    at Class.run (c:\Users\f.dehopre\devs\Portal\frontend\website\node_modules\angular-cli\commands\build.js:51:26)
    at Class.<anonymous> (c:\Users\f.dehopre\devs\Portal\frontend\website\node_modules\angular-cli\angular-cli\lib\models\command.js:152:17)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```
Since the application compiles correctly when the ```ToastsModule``` is not included in the application, I suspect that the problem is in the ng2-toastr package.
I tried to clone and fix the problem by myself but I didn't find a solution.

Angular-CLI version: 
```
angular-cli: 1.0.0-beta.21
node: 6.9.1
os: win32 x64
```
Angular Version: 2.2.1

**Comment by marcovdb** [comment]
The problem is the AoT compiler cannot accept static objects in the forRoot method. It needs a function reference.

Just do this:

```
export function getToastrOptions() {
    return new ToastOptions({
        positionClass: 'toast-bottom-right',
        toastLife: 10000
    });
}

@NgModule({
    imports: [
        ToastModule.forRoot(getToastrOptions)
    ]
});
```

But then you also have to modify toast.module.d.ts to accept a function reference, else the compiler will be very unhappy:

```
import { ModuleWithProviders } from '@angular/core';
import { ToastOptions } from './toast-options';
export declare class ToastModule {
    static forRoot(config: () => ToastOptions | ToastOptions): ModuleWithProviders;
}
```

**Comment by k-schneider** [comment]
To get around this for now what I did was create a config.ts file that just exports:

```
export const toastConfig = {
  animate: 'flyRight',
  positionClass: 'toast-bottom-right'
};
```

And then import that:

```
import { toastConfig } from './config';
const TOAST_OPTIONS: ToastOptions = <any>toastConfig;
```

And then you can just use the constant above in your forRoot call:

`ToastModule.forRoot(TOAST_OPTIONS)`

At the end of the day ToastOptions is just a simple class that defines some properties which is why this works.  If they were marked as optional then that <any> cast wouldn't even needed.

**Comment by FabienDehopre** [comment]
@marcovdb it wouldn't work since the forRoot method does not accept a method.
@k-schneider Indeed, your solution works perfectly. Thank you.
