### ISSUE TITLE
Getting the following error while trying to access toastr

### ISSUE THREAD

**Issue by PonnapallyAbhijith** [PointInside/ng2-toastr#130]
:58186/node_modules/@angular/core/bundles/core.umd.js:3064 EXCEPTION: Uncaught (in promise): Error: Attempt to use a destroyed view: detectChanges
Error: Attempt to use a destroyed view: detectChanges
    at ViewDestroyedError.ZoneAwareError (http://localhost:58186/node_modules/zone.js/dist/zone.js:811:33)
    at ViewDestroyedError.BaseError [as constructor] (http://localhost:58186/node_modules/@angular/core/bundles/core.umd.js:1239:20)
    at new ViewDestroyedError (http://localhost:58186/node_modules/@angular/core/bundles/core.umd.js:6184:20)
    at CompiledTemplate.proxyViewClass.AppView.throwDestroyedError (http://localhost:58186/node_modules/@angular/core/bundles/core.umd.js:12250:76)
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (http://localhost:58186/node_modules/@angular/core/bundles/core.umd.js:12204:22)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (http://localhost:58186/node_modules/@angular/core/bundles/core.umd.js:12353:48)
    at ViewRef_.detectChanges (http://localhost:58186/node_modules/@angular/core/bundles/core.umd.js:9375:24)
    at ToastContainer.addToast (http://localhost:58186/node_modules/ng2-toastr/src/toast-container.component.js:45:18)
    at ToastsManager.setupToast (http://localhost:58186/node_modules/ng2-toastr/src/toast-manager.js:73:33)
    at eval (http://localhost:58186/node_modules/ng2-toastr/src/toast-manager.js:49:27)
    at new ZoneAwarePromise (http://localhost:58186/node_modules/zone.js/dist/zone.js:551:29)
    at ToastsManager.show (http://localhost:58186/node_modules/ng2-toastr/src/toast-manager.js:26:16)
    at ToastsManager.success (http://localhost:58186/node_modules/ng2-toastr/src/toast-manager.js:124:21)
    at SafeSubscriber.eval [as _next] (http://localhost:58186/app/Modules/Survey/SurveySetup/SurveySettings/survey-settings.component.js:118:33)
    at SafeSubscriber.__tryOrUnsub (http://localhost:58186/node_modules/rxjs/Subscriber.js:223:16)

**Comment by pegaltier** [comment]
Same problem happen just in one component..

EXCEPTION: Uncaught (in promise): Error: Attempt to use a destroyed view: detectChanges
Error: Attempt to use a destroyed view: detectChanges
    at ViewDestroyedError.ZoneAwareError (http://localhost:4200/vendor.bundle.js:132310:33)
    at ViewDestroyedError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:11287:16)
    at new ViewDestroyedError (http://localhost:4200/vendor.bundle.js:69413:16)
    at CompiledTemplate.proxyViewClass.AppView.throwDestroyedError (http://localhost:4200/vendor.bundle.js:105395:72)
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (http://localhost:4200/vendor.bundle.js:105349:18)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (http://localhost:4200/vendor.bundle.js:105546:44)
    at ViewRef_.detectChanges (http://localhost:4200/vendor.bundle.js:70354:20)
    at ToastContainer.addToast (http://localhost:4200/vendor.bundle.js:56586:18)
    at ToastsManager.setupToast (http://localhost:4200/vendor.bundle.js:89680:33)
    at http://localhost:4200/vendor.bundle.js:89656:27
    at new ZoneAwarePromise (http://localhost:4200/vendor.bundle.js:132050:29)
    at ToastsManager.show (http://localhost:4200/vendor.bundle.js:89633:16)
    at ToastsManager.info (http://localhost:4200/vendor.bundle.js:89726:21)
    at SettingComponent.webpackJsonp.776.SettingComponent.clickModify (http://localhost:4200/main.bundle.js:7609:21)
    at CompiledTemplate.proxyViewClass.View_SettingComponent0.handleEvent_38 (/AppModule/SettingComponent/component.ngfactory.js:437:34)

**Comment by pegaltier** [comment]
Ok problem solved, you need to remove type="submit" to button

**Comment by PonnapallyAbhijith** [comment]
I do not have a type="submit" button in my HTML. Which button are you referring to? @pegaltier

**Comment by adammfrank** [comment]
@PonnapallyAbhijith Did you find a solution? I am also having this error.

**Comment by pegaltier** [comment]
is due to multiple event during the action cycle example : form submit +
function onclick

**Comment by PonnapallyAbhijith** [comment]
@adammfrank I ended up with 
this.toastr.container = null; 
clearing the container
But it only shows one toastr at a time

**Comment by PonnapallyAbhijith** [comment]
@pegaltier I am only triggering a single event - a button click to save data and show a toastr on success
Any issues with subscriber that I have to check ?

**Comment by vhogemann** [comment]
I get this error when trying to open a toaster from the router.navigate promise, something like that:

```javascript
this.router.navigate(['/somewhere']).then(() => {
    //this.toastr.container = null; <-- fixes the problem
    this.toastr.success('this will trigger the error');
});
```

**Comment by QuentinBrosse** [comment]
You have to call `this.toastr.setRootViewContainerRef(vcr);` only one time, and in your `AppComponent`, not in other components.

Like this:
```javascript
export class AppComponent {
  constructor(public toastr: ToastsManager, vcr: ViewContainerRef) {
    this.toastr.setRootViewContainerRef(vcr);
  }
}
```

Then, you can use you `toastr` in other components like this:

```javascript
@Component({
  selector: 'app-register-form',
  templateUrl: 'sign-up.component.html'
})
export class SignUpComponent {
  
  constructor([...], private toastr: ToastsManager) { [...] }

  [...]
  
  onSubmit() {
    this.router.navigate(['/']).then(() => {
      console.log(this.toastr.success('Nice to meet you.', 'Welcome !'));
    });
  }
}
```

For my part, it solved the issue.

**Comment by dongtong** [comment]
@QuentinBrosse 

Hi, awesome, it is great solution. Thanks

**Comment by tiangolo** [comment]
Thanks @QuentinBrosse ! That solved my problem. It should be stated in the `README`.
