### ISSUE TITLE
If I destroy the view before the toastr dismisses, I get the following error when I initialize the view again

### ISSUE THREAD

**Issue by adammfrank** [PointInside/ng2-toastr#135]
lang.js:130Angular is running in the development mode. Call enableProdMode() to enable the production mode.
error_handler.js:54 EXCEPTION: Uncaught (in promise): Error: Attempt to use a destroyed view: detectChanges
Error: Attempt to use a destroyed view: detectChanges
    at ViewDestroyedError.BaseError [as constructor] (http://localhost:3000/index.js:45899:27)
    at new ViewDestroyedError (http://localhost:3000/index.js:77147:16)
    at CompiledTemplate.proxyViewClass.AppView.throwDestroyedError (http://localhost:3000/index.js:109706:72)
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (http://localhost:3000/index.js:109660:18)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (http://localhost:3000/index.js:109857:44)
    at ViewRef_.detectChanges (http://localhost:3000/index.js:78061:20)
    at ToastContainer.addToast (http://localhost:3000/index.js:64901:18)
    at ToastsManager.setupToast (http://localhost:3000/index.js:86590:33)
    at http://localhost:3000/index.js:86566:27
    at new ZoneAwarePromise (http://localhost:3000/index.js:97437:29)
    at ToastsManager.show (http://localhost:3000/index.js:86543:16)
    at ToastsManager.error (http://localhost:3000/index.js:86631:21)
    at ChartComponent.ngOnChanges (http://localhost:3000/index.js:148351:25)
    at Wrapper_ChartComponent.ngDoCheck (/HierarchyModule/ChartComponent/wrapper.ngfactory.js:44:20)
    at View_HierarchyComponent2.detectChangesInternal (/HierarchyModule/HierarchyComponent/component.ngfactory.js:108:28)
    at View_HierarchyComponent2.AppView.detectChanges (http://localhost:3000/index.js:109662:14)
    at View_HierarchyComponent2.DebugAppView.detectChanges (http://localhost:3000/index.js:109857:44)
    at ViewContainer.detectChangesInNestedViews (http://localhost:3000/index.js:109994:37)
    at CompiledTemplate.proxyViewClass.View_HierarchyComponent0.detectChangesInternal (/HierarchyModule/HierarchyComponent/component.ngfactory.js:232:15)
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (http://localhost:3000/index.js:109662:14)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (http://localhost:3000/index.js:109857:44)
    at CompiledTemplate.proxyViewClass.AppView.internalDetectChanges (http://localhost:3000/index.js:109647:18)
    at CompiledTemplate.proxyViewClass.View_HierarchyComponent_Host0.detectChangesInternal (/HierarchyModule/HierarchyComponent/host.ngfactory.js:32:19)
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (http://localhost:3000/index.js:109662:14)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (http://localhost:3000/index.js:109857:44)
    at ViewContainer.detectChangesInNestedViews (http://localhost:3000/index.js:109994:37)
    at CompiledTemplate.proxyViewClass.View_AppComponent0.detectChangesInternal (/AppModule/AppComponent/component.ngfactory.js:56:14)
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (http://localhost:3000/index.js:109662:14)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (http://localhost:3000/index.js:109857:44)
    at CompiledTemplate.proxyViewClass.AppView.internalDetectChanges (http://localhost:3000/index.js:109647:18)
    at CompiledTemplate.proxyViewClass.View_AppComponent_Host0.detectChangesInternal (/AppModule/AppComponent/host.ngfactory.js:29:19)
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (http://localhost:3000/index.js:109662:14)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (http://localhost:3000/index.js:109857:44)
    at ViewRef_.detectChanges (http://localhost:3000/index.js:78061:20)
    at http://localhost:3000/index.js:58360:67
    at Array.forEach (native)
    at ApplicationRef_.tick (http://localhost:3000/index.js:58360:25)
    at http://localhost:3000/index.js:58279:105
    at ZoneDelegate.invoke (http://localhost:3000/index.js:97151:26)
    at Object.onInvoke (http://localhost:3000/index.js:47555:37)
    at ZoneDelegate.invoke (http://localhost:3000/index.js:97150:32)
    at Zone.run (http://localhost:3000/index.js:97033:43)
    at NgZone.run (http://localhost:3000/index.js:47424:62)
    at Object.next (http://localhost:3000/index.js:58279:81)
    at SafeSubscriber.schedulerFn [as _next] (http://localhost:3000/index.js:60139:52)
    at SafeSubscriber.__tryOrUnsub (http://localhost:3000/index.js:597:16)
    at SafeSubscriber.next (http://localhost:3000/index.js:546:22)
    at Subscriber._next (http://localhost:3000/index.js:499:26)
    at Subscriber.next (http://localhost:3000/index.js:463:18)
    at EventEmitter.Subject.next (http://localhost:3000/index.js:3413:25)
    at EventEmitter.emit (http://localhost:3000/index.js:60125:76)
    at NgZone.checkStable (http://localhost:3000/index.js:47520:40)
    at NgZone.setHasMicrotask (http://localhost:3000/index.js:47604:14)
    at Object.onHasTask (http://localhost:3000/index.js:47567:31)
    at ZoneDelegate.hasTask (http://localhost:3000/index.js:97212:33)
    at ZoneDelegate._updateTaskCount (http://localhost:3000/index.js:97229:26)
    at ZoneDelegate.invokeTask (http://localhost:3000/index.js:97189:26)
    at Zone.runTask (http://localhost:3000/index.js:97073:47)
    at drainMicroTaskQueue (http://localhost:3000/index.js:97320:35)
    at XMLHttpRequest.ZoneTask.invoke (http://localhost:3000/index.js:97258:25)

I think this could be fixed by having a method to immediately destroy the view, which can be called in the onDestroy of the component which contains it.

**Comment by derekshi** [comment]
can you share some code how you destroy the view?

**Comment by dosanias** [comment]
add this function 
ngOnDestroy() {
        
        this.helper.toastr.dispose();
    }

and change in node_modules/ng2-toastr/bundle/toast-manager.js file

replace dispose function to this

ToastsManager.prototype.dispose = function () {
        var _this = this;
		if (_this.container) {
			_this.container.destroy();
			_this.container = null;
		}
    };
