### ISSUE TITLE
Angular 5.0 compatibility

### ISSUE THREAD

**Issue by marcovdb** [PointInside/ng2-toastr#222]
I updated my project to Angular 5.0, but now it won't compile in AOT mode. This is what happens:

```
 10% building modules 0/2 modules 2 active ...rojects\XXX\_dev\src\main.aot.ts
[at-loader] Using typescript@2.4.2 from typescript and "tsconfig.json" from D:\Projects\XXX\_dev/tsconfig.json.
                                                    19% building modules 80/96 modules 16 active ...ragula\components\dragula.provider.jsModuleNotFoundError: Module not found: Error: Can't resolve './toast-options' in 'D:\Projects\XXX\_dev\compiled\node_modules\ng2-toastr\src'
    at factoryCallback (D:\Projects\XXX\_dev\node_modules\webpack\lib\Compilation.js:276:40)
    at factory (D:\Projects\XXX\_dev\node_modules\webpack\lib\NormalModuleFactory.js:235:20)
    at resolver (D:\Projects\XXX\_dev\node_modules\webpack\lib\NormalModuleFactory.js:60:20)
    at asyncLib.parallel (D:\Projects\XXX\_dev\node_modules\webpack\lib\NormalModuleFactory.js:127:20)
    at D:\Projects\XXX\_dev\node_modules\async\dist\async.js:3838:9
    at D:\Projects\XXX\_dev\node_modules\async\dist\async.js:421:16
    at iteratorCallback (D:\Projects\XXX\_dev\node_modules\async\dist\async.js:996:13)
    at D:\Projects\XXX\_dev\node_modules\async\dist\async.js:906:16
    at D:\Projects\XXX\_dev\node_modules\async\dist\async.js:3835:13
    at resolvers.normal.resolve (D:\Projects\XXX\_dev\node_modules\webpack\lib\NormalModuleFactory.js:119:22)
    at onError (D:\Projects\XXX\_dev\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:65:10)
    at loggingCallbackWrapper (D:\Projects\XXX\_dev\node_modules\webpack\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at runAfter (D:\Projects\XXX\_dev\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:158:4)
    at innerCallback (D:\Projects\XXX\_dev\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:146:3)
    at loggingCallbackWrapper (D:\Projects\XXX\_dev\node_modules\webpack\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at next (D:\Projects\XXX\_dev\node_modules\tapable\lib\Tapable.js:252:11)
    at D:\Projects\XXX\_dev\node_modules\webpack\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:40:4
    at loggingCallbackWrapper (D:\Projects\XXX\_dev\node_modules\webpack\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at runAfter (D:\Projects\XXX\_dev\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:158:4)
    at innerCallback (D:\Projects\XXX\_dev\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:146:3)
    at loggingCallbackWrapper (D:\Projects\XXX\_dev\node_modules\webpack\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at next (D:\Projects\XXX\_dev\node_modules\tapable\lib\Tapable.js:252:11)
    at innerCallback (D:\Projects\XXX\_dev\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:144:11)
    at loggingCallbackWrapper (D:\Projects\XXX\_dev\node_modules\webpack\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at next (D:\Projects\XXX\_dev\node_modules\tapable\lib\Tapable.js:249:35)
    at resolver.doResolve.createInnerCallback (D:\Projects\XXX\_dev\node_modules\webpack\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:44:6)
    at loggingCallbackWrapper (D:\Projects\XXX\_dev\node_modules\webpack\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at afterInnerCallback (D:\Projects\XXX\_dev\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:168:10)
    at loggingCallbackWrapper (D:\Projects\XXX\_dev\node_modules\webpack\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
    at next (D:\Projects\XXX\_dev\node_modules\tapable\lib\Tapable.js:252:11)
resolve './toast-options' in 'D:\Projects\XXX\_dev\compiled\node_modules\ng2-toastr\src'
  using description file: D:\Projects\XXX\_dev\package.json (relative path: ./compiled/node_modules/ng2-toastr/src)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: D:\Projects\XXX\_dev\package.json (relative path: ./compiled/node_modules/ng2-toastr/src)
    using description file: D:\Projects\XXX\_dev\package.json (relative path: ./compiled/node_modules/ng2-toastr/src/toast-options)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        D:\Projects\XXX\_dev\compiled\node_modules\ng2-toastr\src\toast-options doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        D:\Projects\XXX\_dev\compiled\node_modules\ng2-toastr\src\toast-options.js doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        D:\Projects\XXX\_dev\compiled\node_modules\ng2-toastr\src\toast-options.ts doesn't exist
      as directory
        D:\Projects\XXX\_dev\compiled\node_modules\ng2-toastr\src\toast-options doesn't exist
```

It was working fine with Angular 4.3...

**Comment by smnbbrv** [comment]
it works for me with typescript@2.6.2

**Comment by darrenjs** [comment]
I'm using Angular5 also, issue I have is that when trying to interate ng2-toastr into an application using  HttpClientModule & HttpClient modules, the ViewContainerRef is no longer found as a provider  (i.e. in the demo programs).

**Comment by oxycoder** [comment]
consider to migrate to ngx-toastr
It have almost same syntax with ng2-toastr, took me 5 min to migrate
