### ISSUE TITLE
Ability to change Toast positionClass

### ISSUE THREAD

**Issue by anarvaez292** [PointInside/ng2-toastr#78]
Looks like you have to setup the position when you first import the module like so:

let options: any = {
  animate: 'flyRight',
  positionClass: 'toast-bottom-right',
};
    
@NgModule({
  imports: [BrowserModule, 
        ToastModule.forRoot(options),
    ],
  declarations: [AppComponent],
  bootstrap: [AppComponent],
})

Is it possible to change the position after it's set?  I see you're able to pass options to toastr.show(), but it's not being overridden. 

Sample code:

let toast: Toast = new Toast('info', 'Hello World ');
        let options = {
        animate: 'flyRight',
        positionClass: 'toast-bottom-left',        
        dismiss: 'controlled',
        };
        this.toastr.show(toast, options)

**Comment by anarvaez292** [comment]
After doing some digging, it looks like the options parameter is for properties on the toast object:

export declare class Toast {
    type: string;
    message: string;
    title: string;
    id: number;
    dismiss: 'auto' | 'click' | 'controlled';
    enableHTML: boolean;
    titleClass: string;
    messageClass: string;
    constructor(type: string, message: string, title?: string);
}

Let me know if there's a intuitive way to change the positioning of a single toast.

**Comment by anarvaez292** [comment]
I figured it out.  I had to create a brand new ToastManager:

    constructor(private app:ApplicationRef, private componentFactoryResolver:ComponentFactoryResolver)

        let toastManager:ToastsManager = new ToastsManager(this.componentFactoryResolver,this.app, options)     
        toastManager.show(toast, options)

Could there be an easier way?

**Comment by brachi-wernick** [comment]
I also need this, any idea? it is important for us

**Comment by derekshi** [comment]
@brachi-wernick , based on simple design initially, we only allow positionClass to be set globally and work consistently across the app. Since people like you are looking for the way to pop toaster anywhere on the screen, we might look into this in later releases. In the meanwhile, you have the workaround as @anarvaez292 posted.

**Comment by brachi-wernick** [comment]
The point is that I want top center position but If I have long text the text is trimmed an I can't see it.
So I go to full width but then it became funny for small text. 
Any other option to deal with the width?

**Comment by anarvaez292** [comment]
You could create your own css class to adjust the container width and pass that class into positionClass.

**Comment by ajohnsonRH** [comment]
The documentation should be updated.

**Comment by drPavka** [comment]
Custom ToastsManager provider

**app.module.ts**
```
@NgModule({
...
  providers: [
    [{
      provide: ToastsManager, useClass: BottomToastsManager
    }]
  ]
})
```

**bottom-toasts-manager.ts**

```
import {ApplicationRef, ComponentFactoryResolver, Injectable} from "@angular/core";
import {ToastOptions, ToastsManager} from "ng2-toastr";
@Injectable()
export class BottomToastsManager extends ToastsManager {
  constructor(componentFactoryResolver: ComponentFactoryResolver, appRef: ApplicationRef, options: ToastOptions) {
    super(componentFactoryResolver, appRef, Object.assign(options, {
      positionClass: 'toast-bottom-center',
      toastLife: 3000
    }));
  }
}
```

**Comment by WWind220** [comment]
Here is my solution
`import {ToastOptions} from 'ng2-toastr';

export class CustomOption extends ToastOptions {
constructor(){
        super();
        this.positionClass='toast-bottom-center';
    }
}
`

**Comment by Herbis** [comment]
To update @drPavka workaround with the latest version (at the moment), where the constructor signature for ToastsManager has changed.

**bottom-toasts-manager.ts**
```
import {ApplicationRef, ComponentFactoryResolver, Injectable, NgZone} from "@angular/core";
import {ToastOptions, ToastsManager} from "ng2-toastr";
@Injectable()
export class BottomToastsManager extends ToastsManager {
  constructor(componentFactoryResolver: ComponentFactoryResolver, ngZone: NgZone, appRef: ApplicationRef, options: ToastOptions) {
    super(componentFactoryResolver, ngZone, appRef, Object.assign(options, {
      positionClass: "toast-bottom-center",
      toastLife: 3000
    }));
  }
}
```

**Comment by mani47** [comment]
Using Herbis recommendation I'm getting this error:

> Error: (SystemJS) Object prototype may only be an Object or null: undefined
> 	TypeError: Object prototype may only be an Object or null: undefined
> 	    at setPrototypeOf (<anonymous>)
> 	    at __extends (http://localhost:9208/scripts/angular/app/bottom-toasts-manager.js:7:9)
> 	    at eval (http://localhost:9208/scripts/angular/app/bottom-toasts-manager.js:25:5)
> 	    at Object.eval (http://localhost:9208/scripts/angular/app/bottom-toasts-manager.js:33:2)
> 	    at eval (http://localhost:9208/scripts/angular/app/bottom-toasts-manager.js:40:4)
> 	    at eval (http://localhost:9208/scripts/angular/app/bottom-toasts-manager.js:41:3)
> 	    at eval (<anonymous>)
> 	Evaluating http://localhost:9208/scripts/angular/app/bottom-toasts-manager.js
> 	Evaluating http://localhost:9208/scripts/angular/app/app.module.js
> 	Evaluating http://localhost:9208/scripts/angular/main.js
> 	Error loading http://localhost:9208/scripts/angular/main.js
> 	    at setPrototypeOf (<anonymous>)
> 	    at __extends (http://localhost:9208/scripts/angular/app/bottom-toasts-manager.js:7:9)
> 	    at eval (http://localhost:9208/scripts/angular/app/bottom-toasts-manager.js:25:5)
> 	    at Object.eval (http://localhost:9208/scripts/angular/app/bottom-toasts-manager.js:33:2)
> 	    at eval (http://localhost:9208/scripts/angular/app/bottom-toasts-manager.js:40:4)
> 	    at eval (http://localhost:9208/scripts/angular/app/bottom-toasts-manager.js:41:3)
> 	    at eval (<anonymous>)
> 	Evaluating http://localhost:9208/scripts/angular/app/bottom-toasts-manager.js
> 	Evaluating http://localhost:9208/scripts/angular/app/app.module.js
> 	Evaluating http://localhost:9208/scripts/angular/main.js
> 	Error loading http://localhost:9208/scripts/angular/main.js
>
