### ISSUE TITLE
AoT compilation fails

### ISSUE THREAD

**Issue by marcovdb** [PointInside/ng2-toastr#94]
I'm attempting to use AoT compilation for my project since everyone is raving about it, but I'm running into an issue with ng2-toastr. This is what it's telling me:

    Module not found: Error: Can't resolve '../node_modules/@angular/common/src/directives/ng_for.ngfactory' in 'c:\xampp\htdocs\project\_dev\node_modules\ng2-toastr\src'
        at c:\xampp\htdocs\project\_dev\node_modules\webpack\lib\Compilation.js:232:38
        at onDoneResolving (c:\xampp\htdocs\project\_dev\node_modules\webpack\lib\NormalModuleFactory.js:40:20)
        at c:\xampp\htdocs\project\_dev\node_modules\webpack\lib\NormalModuleFactory.js:117:20
        at c:\xampp\htdocs\project\_dev\node_modules\webpack\node_modules\async\dist\async.js:3853:9
        at c:\xampp\htdocs\project\_dev\node_modules\webpack\node_modules\async\dist\async.js:484:16
        at iteratorCallback (c:\xampp\htdocs\project\_dev\node_modules\webpack\node_modules\async\dist\async.js:1082:13)
        at c:\xampp\htdocs\project\_dev\node_modules\webpack\node_modules\async\dist\async.js:988:16
        at c:\xampp\htdocs\project\_dev\node_modules\webpack\node_modules\async\dist\async.js:3850:13
        at apply (c:\xampp\htdocs\project\_dev\node_modules\webpack\node_modules\async\dist\async.js:41:25)
        at c:\xampp\htdocs\project\_dev\node_modules\webpack\node_modules\async\dist\async.js:76:12
        at c:\xampp\htdocs\project\_dev\node_modules\webpack\lib\NormalModuleFactory.js:112:22
        at onResolved (c:\xampp\htdocs\project\_dev\node_modules\enhanced-resolve\lib\Resolver.js:70:11)
        at loggingCallbackWrapper (c:\xampp\htdocs\project\_dev\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
        at afterInnerCallback (c:\xampp\htdocs\project\_dev\node_modules\enhanced-resolve\lib\Resolver.js:138:10)
        at loggingCallbackWrapper (c:\xampp\htdocs\project\_dev\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
        at Resolver.applyPluginsAsyncSeriesBailResult1 (c:\xampp\htdocs\project\_dev\node_modules\tapable\lib\Tapable.js:108:46)
        at innerCallback (c:\xampp\htdocs\project\_dev\node_modules\enhanced-resolve\lib\Resolver.js:125:19)
        at loggingCallbackWrapper (c:\xampp\htdocs\project\_dev\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
        at c:\xampp\htdocs\project\_dev\node_modules\tapable\lib\Tapable.js:210:15
        at c:\xampp\htdocs\project\_dev\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:39:4
        at loggingCallbackWrapper (c:\xampp\htdocs\project\_dev\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
        at afterInnerCallback (c:\xampp\htdocs\project\_dev\node_modules\enhanced-resolve\lib\Resolver.js:138:10)
        at loggingCallbackWrapper (c:\xampp\htdocs\project\_dev\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
        at Resolver.applyPluginsAsyncSeriesBailResult1 (c:\xampp\htdocs\project\_dev\node_modules\tapable\lib\Tapable.js:108:46)
        at innerCallback (c:\xampp\htdocs\project\_dev\node_modules\enhanced-resolve\lib\Resolver.js:125:19)
        at loggingCallbackWrapper (c:\xampp\htdocs\project\_dev\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
        at c:\xampp\htdocs\project\_dev\node_modules\tapable\lib\Tapable.js:210:15
        at innerCallback (c:\xampp\htdocs\project\_dev\node_modules\enhanced-resolve\lib\Resolver.js:123:11)
        at loggingCallbackWrapper (c:\xampp\htdocs\project\_dev\node_modules\enhanced-resolve\lib\createInnerCallback.js:31:19)
        at c:\xampp\htdocs\project\_dev\node_modules\tapable\lib\Tapable.js:210:15
    resolve '../node_modules/@angular/common/src/directives/ng_for.ngfactory' in 'c:\xampp\htdocs\project\_dev\node_modules\ng2-toastr\src'
      using description file: c:\xampp\htdocs\project\_dev\node_modules\ng2-toastr\package.json (relative path: ./src)
        Field 'browser' doesn't contain a valid alias configuration
      after using description file: c:\xampp\htdocs\project\_dev\node_modules\ng2-toastr\package.json (relative path: ./src)
        using description file: c:\xampp\htdocs\project\_dev\node_modules\ng2-toastr\package.json (relative path: ./node_modules/@angular/common/src/directives/ng_for.ngfactory)
          as directory
            c:\xampp\htdocs\project\_dev\node_modules\ng2-toastr\node_modules\@angular\common\src\directives\ng_for.ngfactory doesn't exist
          no extension
            Field 'browser' doesn't contain a valid alias configuration
            c:\xampp\htdocs\project\_dev\node_modules\ng2-toastr\node_modules\@angular\common\src\directives\ng_for.ngfactory doesn't exist
          .js
            Field 'browser' doesn't contain a valid alias configuration
            c:\xampp\htdocs\project\_dev\node_modules\ng2-toastr\node_modules\@angular\common\src\directives\ng_for.ngfactory.js doesn't exist
          .ts
            Field 'browser' doesn't contain a valid alias configuration
            c:\xampp\htdocs\project\_dev\node_modules\ng2-toastr\node_modules\@angular\common\src\directives\ng_for.ngfactory.ts doesn't exist

I can work around this by installing '@angular/common' into the ng2-toastr folder, but if I do that the AoT compiler also compiles the Angular module into the bundle and it seems to add considerably to its size.

![toastraot](https://cloud.githubusercontent.com/assets/10506742/20476623/40d704a6-afd2-11e6-84c2-071a453ba440.PNG)

Any ideas? :)

**Comment by marcovdb** [comment]
I think I figured out why it's doing this. In toast-container.component.ngfactory.js there are a couple of references like this:

```
var import22 = require('../node_modules/@angular/common/src/directives/ng_if.ngfactory');
var import23 = require('../node_modules/@angular/common/src/directives/ng_switch.ngfactory');
```

Now as to why it's like that... I don't know. But it's kind of wrong :) I'll see what more I can dig up.

**Comment by marcovdb** [comment]
I've not had this issue since moving away from the @ngtools/webpack plugin. So I can only assume that had something to do with it.
